### ISSUE TITLE
Goto method definition bug when mixed type

### ISSUE THREAD

**Issue by xiaohuilam** [tsufeki/tenkawa-php-language-server#23]
when i declare a var with mixed class (`A|B` or `A&B`), the method `test` which exists class A only, can not be intelesense from the call by this var.

```php
<?php
class A
{
    public function test()
    {
    }
}

class B
{
}

/**
 * @var A|B
 */
$x = new A;
$x->test();
```

and an error occur 
```
2018-12-16T15:45:39+00:00 pid=86702 ERROR Exception during PHPStan analysis: PHPStan\Broker\ClassNotFoundException: Class \A was not found while trying to analyse it - autoloading is probably not configured properly. in /Users/***/.vscode/extensions/tsufeki.tenkawa-php-0.3.3/vendor/tsufeki/tenkawa-php-language-server/src/Tsufeki/Tenkawa/Php/PhpStan/IndexBroker.php:182
```

But if i declare the var as single type, or just put same method at the class B, it works fine.

**Comment by tsufeki** [comment]
That's how union type `A|B` work: language server does not know if `$x` is actually `A` or actually `B`. Since method is only on `A`, it is ignored as it may be inaccessible. You need an explicit check:

```php
/**
 * @var A|B
 */
$x = ...
if ($x instanceof A) {
    $x->test();
}
```

For `A&B`, an object can't be an instance of two unrelated *classes* at the same time so this type is an error. However, if `B` was an interface it would work:

```php
<?php
class A
{
    public function test()
    {
    }
}

interface B
{
}

/**
 * @var A&B
 */
$x = ...
$x->test();
```

Tenkawa is very strict about this. I guess it could make sense to relax this behaviour a bit, but I need give it some more thought.

Anyway, thank you for reporting this. If you find any more issues, feel free to report them as well.

btw I can recommend an article [Union Types vs. Intersection Types](https://medium.com/@ondrejmirtes/union-types-vs-intersection-types-fd44a8eacbb)

**Comment by xiaohuilam** [comment]
Usually, Go to definition code was presented in vendor, which not override-able by this project owner.
For example, the laravel framework's `response()` helper method, it defines to return `@return \Illuminate\Http\Response|\Illuminate\Contracts\Routing\ResponseFactory`,  when i write `reponse()->json()`, i think i shouldn't to check it like this:
```php
$reponse = reponse();
if ($reponse instanceof \Illuminate\Contracts\Routing\ResponseFactory) {
    reponse()->json(['success' => true]);
}
```

**Comment by tsufeki** [comment]
I relaxed the logic for union types in completions, go to, hovers etc . (03be2aff378b7f5bd3f87744237df262d6ffd020), they should work as you expect.

But `reponse()->json()` will still be underlined as a warning - it'll be fixed when I integrate laravel extension (hopefully soon).

Thanks.
